# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/individuals/implementations/NetworkIndividual.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.individuals import Individual_pb2 as LAMARCK__ML_dot_individuals_dot_Individual__pb2
from LAMARCK_ML.architectures import NeuralNetwork_pb2 as LAMARCK__ML_dot_architectures_dot_NeuralNetwork__pb2
from LAMARCK_ML.architectures.losses import Loss_pb2 as LAMARCK__ML_dot_architectures_dot_losses_dot_Loss__pb2
from LAMARCK_ML.data_util import TypeShape_pb2 as LAMARCK__ML_dot_data__util_dot_TypeShape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/individuals/implementations/NetworkIndividual.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n>LAMARCK_ML/individuals/implementations/NetworkIndividual.proto\x12\nLAMARCK_ML\x1a\'LAMARCK_ML/individuals/Individual.proto\x1a,LAMARCK_ML/architectures/NeuralNetwork.proto\x1a*LAMARCK_ML/architectures/losses/Loss.proto\x1a$LAMARCK_ML/data_util/TypeShape.proto\"\xde\x02\n\x16NetworkIndividualProto\x12\x10\n\x08\x63ls_name\x18\x01 \x01(\t\x12\x33\n\x0e\x62\x61seIndividual\x18\n \x01(\x0b\x32\x1b.LAMARCK_ML.IndividualProto\x12\x30\n\x08networks\x18\x0b \x03(\x0b\x32\x1e.LAMARCK_ML.NeuralNetworkProto\x12H\n\x0c\x64\x61ta_sources\x18\x0c \x03(\x0b\x32\x32.LAMARCK_ML.NetworkIndividualProto.DataSourceProto\x12%\n\x06losses\x18\r \x03(\x0b\x32\x15.LAMARCK_ML.LossProto\x1aZ\n\x0f\x44\x61taSourceProto\x12\x0f\n\x07id_name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\'\n\x03tsp\x18\x03 \x01(\x0b\x32\x1a.LAMARCK_ML.TypeShapeProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_individuals_dot_Individual__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_NeuralNetwork__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_losses_dot_Loss__pb2.DESCRIPTOR,LAMARCK__ML_dot_data__util_dot_TypeShape__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NETWORKINDIVIDUALPROTO_DATASOURCEPROTO = _descriptor.Descriptor(
  name='DataSourceProto',
  full_name='LAMARCK_ML.NetworkIndividualProto.DataSourceProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.NetworkIndividualProto.DataSourceProto.id_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='LAMARCK_ML.NetworkIndividualProto.DataSourceProto.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tsp', full_name='LAMARCK_ML.NetworkIndividualProto.DataSourceProto.tsp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=598,
)

_NETWORKINDIVIDUALPROTO = _descriptor.Descriptor(
  name='NetworkIndividualProto',
  full_name='LAMARCK_ML.NetworkIndividualProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='LAMARCK_ML.NetworkIndividualProto.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseIndividual', full_name='LAMARCK_ML.NetworkIndividualProto.baseIndividual', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networks', full_name='LAMARCK_ML.NetworkIndividualProto.networks', index=2,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_sources', full_name='LAMARCK_ML.NetworkIndividualProto.data_sources', index=3,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='losses', full_name='LAMARCK_ML.NetworkIndividualProto.losses', index=4,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NETWORKINDIVIDUALPROTO_DATASOURCEPROTO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=598,
)

_NETWORKINDIVIDUALPROTO_DATASOURCEPROTO.fields_by_name['tsp'].message_type = LAMARCK__ML_dot_data__util_dot_TypeShape__pb2._TYPESHAPEPROTO
_NETWORKINDIVIDUALPROTO_DATASOURCEPROTO.containing_type = _NETWORKINDIVIDUALPROTO
_NETWORKINDIVIDUALPROTO.fields_by_name['baseIndividual'].message_type = LAMARCK__ML_dot_individuals_dot_Individual__pb2._INDIVIDUALPROTO
_NETWORKINDIVIDUALPROTO.fields_by_name['networks'].message_type = LAMARCK__ML_dot_architectures_dot_NeuralNetwork__pb2._NEURALNETWORKPROTO
_NETWORKINDIVIDUALPROTO.fields_by_name['data_sources'].message_type = _NETWORKINDIVIDUALPROTO_DATASOURCEPROTO
_NETWORKINDIVIDUALPROTO.fields_by_name['losses'].message_type = LAMARCK__ML_dot_architectures_dot_losses_dot_Loss__pb2._LOSSPROTO
DESCRIPTOR.message_types_by_name['NetworkIndividualProto'] = _NETWORKINDIVIDUALPROTO

NetworkIndividualProto = _reflection.GeneratedProtocolMessageType('NetworkIndividualProto', (_message.Message,), dict(

  DataSourceProto = _reflection.GeneratedProtocolMessageType('DataSourceProto', (_message.Message,), dict(
    DESCRIPTOR = _NETWORKINDIVIDUALPROTO_DATASOURCEPROTO,
    __module__ = 'LAMARCK_ML.individuals.implementations.NetworkIndividual_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.NetworkIndividualProto.DataSourceProto)
    ))
  ,
  DESCRIPTOR = _NETWORKINDIVIDUALPROTO,
  __module__ = 'LAMARCK_ML.individuals.implementations.NetworkIndividual_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.NetworkIndividualProto)
  ))
_sym_db.RegisterMessage(NetworkIndividualProto)
_sym_db.RegisterMessage(NetworkIndividualProto.DataSourceProto)


# @@protoc_insertion_point(module_scope)
