# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/architectures/variables/Variable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import DType_pb2 as LAMARCK__ML_dot_data__util_dot_DType__pb2
from LAMARCK_ML.data_util import Shape_pb2 as LAMARCK__ML_dot_data__util_dot_Shape__pb2
from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/architectures/variables/Variable.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n1LAMARCK_ML/architectures/variables/Variable.proto\x12\nLAMARCK_ML\x1a LAMARCK_ML/data_util/DType.proto\x1a LAMARCK_ML/data_util/Shape.proto\x1a$LAMARCK_ML/data_util/Attribute.proto\"\x93\x05\n\rVariableProto\x12%\n\x05\x64type\x18\x01 \x01(\x0b\x32\x16.LAMARCK_ML.DTypeProto\x12%\n\x05shape\x18\x02 \x01(\x0b\x32\x16.LAMARCK_ML.ShapeProto\x12\x11\n\ttrainable\x18\x03 \x01(\x08\x12\x0c\n\x04name\x18\x04 \x01(\t\x12?\n\x0binitializer\x18\x07 \x01(\x0b\x32*.LAMARCK_ML.VariableProto.InitializerProto\x12\x45\n\x0eregularisation\x18\x08 \x01(\x0b\x32-.LAMARCK_ML.VariableProto.RegularisationProto\x12\x11\n\tbytes_val\x18\n \x03(\x0c\x12\x10\n\x08half_val\x18\x0b \x03(\x05\x12\x11\n\tfloat_val\x18\x0c \x03(\x02\x12\x12\n\ndouble_val\x18\r \x03(\x01\x12\x0f\n\x07int_val\x18\x0e \x03(\x05\x12\x12\n\nstring_val\x18\x0f \x03(\t\x12\x14\n\x0cscomplex_val\x18\x10 \x03(\x02\x12\x11\n\tint64_val\x18\x11 \x03(\x03\x12\x10\n\x08\x62ool_val\x18\x12 \x03(\x08\x12\x14\n\x0c\x64\x63omplex_val\x18\x13 \x03(\x01\x12\x12\n\nuint32_val\x18\x14 \x03(\r\x12\x12\n\nuint64_val\x18\x15 \x03(\x04\x1aN\n\x10InitializerProto\x12\x10\n\x08\x63ls_name\x18\x01 \x01(\t\x12(\n\x04\x61ttr\x18\x02 \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProto\x1aQ\n\x13RegularisationProto\x12\x10\n\x08\x63ls_name\x18\x01 \x01(\t\x12(\n\x04\x61ttr\x18\x02 \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_DType__pb2.DESCRIPTOR,LAMARCK__ML_dot_data__util_dot_Shape__pb2.DESCRIPTOR,LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VARIABLEPROTO_INITIALIZERPROTO = _descriptor.Descriptor(
  name='InitializerProto',
  full_name='LAMARCK_ML.VariableProto.InitializerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='LAMARCK_ML.VariableProto.InitializerProto.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.VariableProto.InitializerProto.attr', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=748,
)

_VARIABLEPROTO_REGULARISATIONPROTO = _descriptor.Descriptor(
  name='RegularisationProto',
  full_name='LAMARCK_ML.VariableProto.RegularisationProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='LAMARCK_ML.VariableProto.RegularisationProto.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.VariableProto.RegularisationProto.attr', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=831,
)

_VARIABLEPROTO = _descriptor.Descriptor(
  name='VariableProto',
  full_name='LAMARCK_ML.VariableProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='LAMARCK_ML.VariableProto.dtype', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='LAMARCK_ML.VariableProto.shape', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trainable', full_name='LAMARCK_ML.VariableProto.trainable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='LAMARCK_ML.VariableProto.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='LAMARCK_ML.VariableProto.initializer', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='regularisation', full_name='LAMARCK_ML.VariableProto.regularisation', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_val', full_name='LAMARCK_ML.VariableProto.bytes_val', index=6,
      number=10, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='half_val', full_name='LAMARCK_ML.VariableProto.half_val', index=7,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='LAMARCK_ML.VariableProto.float_val', index=8,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_val', full_name='LAMARCK_ML.VariableProto.double_val', index=9,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_val', full_name='LAMARCK_ML.VariableProto.int_val', index=10,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='LAMARCK_ML.VariableProto.string_val', index=11,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scomplex_val', full_name='LAMARCK_ML.VariableProto.scomplex_val', index=12,
      number=16, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int64_val', full_name='LAMARCK_ML.VariableProto.int64_val', index=13,
      number=17, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='LAMARCK_ML.VariableProto.bool_val', index=14,
      number=18, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dcomplex_val', full_name='LAMARCK_ML.VariableProto.dcomplex_val', index=15,
      number=19, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_val', full_name='LAMARCK_ML.VariableProto.uint32_val', index=16,
      number=20, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64_val', full_name='LAMARCK_ML.VariableProto.uint64_val', index=17,
      number=21, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VARIABLEPROTO_INITIALIZERPROTO, _VARIABLEPROTO_REGULARISATIONPROTO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=831,
)

_VARIABLEPROTO_INITIALIZERPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
_VARIABLEPROTO_INITIALIZERPROTO.containing_type = _VARIABLEPROTO
_VARIABLEPROTO_REGULARISATIONPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
_VARIABLEPROTO_REGULARISATIONPROTO.containing_type = _VARIABLEPROTO
_VARIABLEPROTO.fields_by_name['dtype'].message_type = LAMARCK__ML_dot_data__util_dot_DType__pb2._DTYPEPROTO
_VARIABLEPROTO.fields_by_name['shape'].message_type = LAMARCK__ML_dot_data__util_dot_Shape__pb2._SHAPEPROTO
_VARIABLEPROTO.fields_by_name['initializer'].message_type = _VARIABLEPROTO_INITIALIZERPROTO
_VARIABLEPROTO.fields_by_name['regularisation'].message_type = _VARIABLEPROTO_REGULARISATIONPROTO
DESCRIPTOR.message_types_by_name['VariableProto'] = _VARIABLEPROTO

VariableProto = _reflection.GeneratedProtocolMessageType('VariableProto', (_message.Message,), dict(

  InitializerProto = _reflection.GeneratedProtocolMessageType('InitializerProto', (_message.Message,), dict(
    DESCRIPTOR = _VARIABLEPROTO_INITIALIZERPROTO,
    __module__ = 'LAMARCK_ML.architectures.variables.Variable_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.VariableProto.InitializerProto)
    ))
  ,

  RegularisationProto = _reflection.GeneratedProtocolMessageType('RegularisationProto', (_message.Message,), dict(
    DESCRIPTOR = _VARIABLEPROTO_REGULARISATIONPROTO,
    __module__ = 'LAMARCK_ML.architectures.variables.Variable_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.VariableProto.RegularisationProto)
    ))
  ,
  DESCRIPTOR = _VARIABLEPROTO,
  __module__ = 'LAMARCK_ML.architectures.variables.Variable_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.VariableProto)
  ))
_sym_db.RegisterMessage(VariableProto)
_sym_db.RegisterMessage(VariableProto.InitializerProto)
_sym_db.RegisterMessage(VariableProto.RegularisationProto)


# @@protoc_insertion_point(module_scope)
