# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/models/GenerationalModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.individuals import Individual_pb2 as LAMARCK__ML_dot_individuals_dot_Individual__pb2
from LAMARCK_ML.reproduction import Ancestry_pb2 as LAMARCK__ML_dot_reproduction_dot_Ancestry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/models/GenerationalModel.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n)LAMARCK_ML/models/GenerationalModel.proto\x12\nLAMARCK_ML\x1a\'LAMARCK_ML/individuals/Individual.proto\x1a&LAMARCK_ML/reproduction/Ancestry.proto\"\xdf\x03\n\x16GenerationalModelProto\x12/\n\ngeneration\x18\x01 \x03(\x0b\x32\x1b.LAMARCK_ML.IndividualProto\x12.\n\tselection\x18\x02 \x03(\x0b\x32\x1b.LAMARCK_ML.IndividualProto\x12J\n\x0creproduction\x18\x03 \x03(\x0b\x32\x34.LAMARCK_ML.GenerationalModelProto.ReproductionProto\x12T\n\x12reproduction_pools\x18\x04 \x03(\x0b\x32\x38.LAMARCK_ML.GenerationalModelProto.ReproductionPoolProto\x12\x16\n\x0egeneration_idx\x18\x05 \x01(\x03\x12\r\n\x05state\x18\x06 \x01(\x05\x1aI\n\x15ReproductionPoolProto\x12\x30\n\x0bindividuals\x18\x01 \x03(\x0b\x32\x1b.LAMARCK_ML.IndividualProto\x1aP\n\x11ReproductionProto\x12\x0e\n\x06method\x18\x01 \x01(\t\x12+\n\x08\x61ncestry\x18\x02 \x03(\x0b\x32\x19.LAMARCK_ML.AncestryProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_individuals_dot_Individual__pb2.DESCRIPTOR,LAMARCK__ML_dot_reproduction_dot_Ancestry__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO = _descriptor.Descriptor(
  name='ReproductionPoolProto',
  full_name='LAMARCK_ML.GenerationalModelProto.ReproductionPoolProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='individuals', full_name='LAMARCK_ML.GenerationalModelProto.ReproductionPoolProto.individuals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=536,
)

_GENERATIONALMODELPROTO_REPRODUCTIONPROTO = _descriptor.Descriptor(
  name='ReproductionProto',
  full_name='LAMARCK_ML.GenerationalModelProto.ReproductionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='LAMARCK_ML.GenerationalModelProto.ReproductionProto.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ancestry', full_name='LAMARCK_ML.GenerationalModelProto.ReproductionProto.ancestry', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=618,
)

_GENERATIONALMODELPROTO = _descriptor.Descriptor(
  name='GenerationalModelProto',
  full_name='LAMARCK_ML.GenerationalModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generation', full_name='LAMARCK_ML.GenerationalModelProto.generation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selection', full_name='LAMARCK_ML.GenerationalModelProto.selection', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reproduction', full_name='LAMARCK_ML.GenerationalModelProto.reproduction', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reproduction_pools', full_name='LAMARCK_ML.GenerationalModelProto.reproduction_pools', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generation_idx', full_name='LAMARCK_ML.GenerationalModelProto.generation_idx', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='LAMARCK_ML.GenerationalModelProto.state', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO, _GENERATIONALMODELPROTO_REPRODUCTIONPROTO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=618,
)

_GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO.fields_by_name['individuals'].message_type = LAMARCK__ML_dot_individuals_dot_Individual__pb2._INDIVIDUALPROTO
_GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO.containing_type = _GENERATIONALMODELPROTO
_GENERATIONALMODELPROTO_REPRODUCTIONPROTO.fields_by_name['ancestry'].message_type = LAMARCK__ML_dot_reproduction_dot_Ancestry__pb2._ANCESTRYPROTO
_GENERATIONALMODELPROTO_REPRODUCTIONPROTO.containing_type = _GENERATIONALMODELPROTO
_GENERATIONALMODELPROTO.fields_by_name['generation'].message_type = LAMARCK__ML_dot_individuals_dot_Individual__pb2._INDIVIDUALPROTO
_GENERATIONALMODELPROTO.fields_by_name['selection'].message_type = LAMARCK__ML_dot_individuals_dot_Individual__pb2._INDIVIDUALPROTO
_GENERATIONALMODELPROTO.fields_by_name['reproduction'].message_type = _GENERATIONALMODELPROTO_REPRODUCTIONPROTO
_GENERATIONALMODELPROTO.fields_by_name['reproduction_pools'].message_type = _GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO
DESCRIPTOR.message_types_by_name['GenerationalModelProto'] = _GENERATIONALMODELPROTO

GenerationalModelProto = _reflection.GeneratedProtocolMessageType('GenerationalModelProto', (_message.Message,), dict(

  ReproductionPoolProto = _reflection.GeneratedProtocolMessageType('ReproductionPoolProto', (_message.Message,), dict(
    DESCRIPTOR = _GENERATIONALMODELPROTO_REPRODUCTIONPOOLPROTO,
    __module__ = 'LAMARCK_ML.models.GenerationalModel_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.GenerationalModelProto.ReproductionPoolProto)
    ))
  ,

  ReproductionProto = _reflection.GeneratedProtocolMessageType('ReproductionProto', (_message.Message,), dict(
    DESCRIPTOR = _GENERATIONALMODELPROTO_REPRODUCTIONPROTO,
    __module__ = 'LAMARCK_ML.models.GenerationalModel_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.GenerationalModelProto.ReproductionProto)
    ))
  ,
  DESCRIPTOR = _GENERATIONALMODELPROTO,
  __module__ = 'LAMARCK_ML.models.GenerationalModel_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.GenerationalModelProto)
  ))
_sym_db.RegisterMessage(GenerationalModelProto)
_sym_db.RegisterMessage(GenerationalModelProto.ReproductionPoolProto)
_sym_db.RegisterMessage(GenerationalModelProto.ReproductionProto)


# @@protoc_insertion_point(module_scope)
