# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/data_util/DType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/data_util/DType.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n LAMARCK_ML/data_util/DType.proto\x12\nLAMARCK_ML\"G\n\nDTypeProto\x12\'\n\x08type_val\x18\x01 \x01(\x0e\x32\x15.LAMARCK_ML.TypeProto\x12\x10\n\x08\x62its_val\x18\x02 \x01(\x05*m\n\tTypeProto\x12\x0c\n\x08\x44Invalid\x10\x00\x12\x0b\n\x07\x44\x42inary\x10\n\x12\t\n\x05\x44UInt\x10\x0b\x12\x08\n\x04\x44Int\x10\x0c\x12\n\n\x06\x44\x46loat\x10\r\x12\x0c\n\x08\x44\x43omplex\x10\x0e\x12\t\n\x05\x44\x42ool\x10\x14\x12\x0b\n\x07\x44String\x10\x15\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPEPROTO = _descriptor.EnumDescriptor(
  name='TypeProto',
  full_name='LAMARCK_ML.TypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DInvalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DBinary', index=1, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DUInt', index=2, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DInt', index=3, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DFloat', index=4, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DComplex', index=5, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DBool', index=6, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DString', index=7, number=21,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_TYPEPROTO)

TypeProto = enum_type_wrapper.EnumTypeWrapper(_TYPEPROTO)
DInvalid = 0
DBinary = 10
DUInt = 11
DInt = 12
DFloat = 13
DComplex = 14
DBool = 20
DString = 21



_DTYPEPROTO = _descriptor.Descriptor(
  name='DTypeProto',
  full_name='LAMARCK_ML.DTypeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_val', full_name='LAMARCK_ML.DTypeProto.type_val', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bits_val', full_name='LAMARCK_ML.DTypeProto.bits_val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=119,
)

_DTYPEPROTO.fields_by_name['type_val'].enum_type = _TYPEPROTO
DESCRIPTOR.message_types_by_name['DTypeProto'] = _DTYPEPROTO
DESCRIPTOR.enum_types_by_name['TypeProto'] = _TYPEPROTO

DTypeProto = _reflection.GeneratedProtocolMessageType('DTypeProto', (_message.Message,), dict(
  DESCRIPTOR = _DTYPEPROTO,
  __module__ = 'LAMARCK_ML.data_util.DType_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.DTypeProto)
  ))
_sym_db.RegisterMessage(DTypeProto)


# @@protoc_insertion_point(module_scope)
