# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/data_util/Shape.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/data_util/Shape.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n LAMARCK_ML/data_util/Shape.proto\x12\nLAMARCK_ML\"X\n\nShapeProto\x12\'\n\x03\x64im\x18\x01 \x03(\x0b\x32\x1a.LAMARCK_ML.ShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SHAPEPROTO_DIM = _descriptor.Descriptor(
  name='Dim',
  full_name='LAMARCK_ML.ShapeProto.Dim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='LAMARCK_ML.ShapeProto.Dim.size', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='LAMARCK_ML.ShapeProto.Dim.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=136,
)

_SHAPEPROTO = _descriptor.Descriptor(
  name='ShapeProto',
  full_name='LAMARCK_ML.ShapeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='LAMARCK_ML.ShapeProto.dim', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SHAPEPROTO_DIM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=136,
)

_SHAPEPROTO_DIM.containing_type = _SHAPEPROTO
_SHAPEPROTO.fields_by_name['dim'].message_type = _SHAPEPROTO_DIM
DESCRIPTOR.message_types_by_name['ShapeProto'] = _SHAPEPROTO

ShapeProto = _reflection.GeneratedProtocolMessageType('ShapeProto', (_message.Message,), dict(

  Dim = _reflection.GeneratedProtocolMessageType('Dim', (_message.Message,), dict(
    DESCRIPTOR = _SHAPEPROTO_DIM,
    __module__ = 'LAMARCK_ML.data_util.Shape_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.ShapeProto.Dim)
    ))
  ,
  DESCRIPTOR = _SHAPEPROTO,
  __module__ = 'LAMARCK_ML.data_util.Shape_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.ShapeProto)
  ))
_sym_db.RegisterMessage(ShapeProto)
_sym_db.RegisterMessage(ShapeProto.Dim)


# @@protoc_insertion_point(module_scope)
