# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/data_util/TypeShape.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import Shape_pb2 as LAMARCK__ML_dot_data__util_dot_Shape__pb2
from LAMARCK_ML.data_util import DType_pb2 as LAMARCK__ML_dot_data__util_dot_DType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/data_util/TypeShape.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n$LAMARCK_ML/data_util/TypeShape.proto\x12\nLAMARCK_ML\x1a LAMARCK_ML/data_util/Shape.proto\x1a LAMARCK_ML/data_util/DType.proto\"w\n\x0eTypeShapeProto\x12\x0f\n\x07id_name\x18\x01 \x01(\t\x12)\n\tdtype_val\x18\x02 \x01(\x0b\x32\x16.LAMARCK_ML.DTypeProto\x12)\n\tshape_val\x18\x03 \x01(\x0b\x32\x16.LAMARCK_ML.ShapeProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_Shape__pb2.DESCRIPTOR,LAMARCK__ML_dot_data__util_dot_DType__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TYPESHAPEPROTO = _descriptor.Descriptor(
  name='TypeShapeProto',
  full_name='LAMARCK_ML.TypeShapeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.TypeShapeProto.id_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype_val', full_name='LAMARCK_ML.TypeShapeProto.dtype_val', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape_val', full_name='LAMARCK_ML.TypeShapeProto.shape_val', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=239,
)

_TYPESHAPEPROTO.fields_by_name['dtype_val'].message_type = LAMARCK__ML_dot_data__util_dot_DType__pb2._DTYPEPROTO
_TYPESHAPEPROTO.fields_by_name['shape_val'].message_type = LAMARCK__ML_dot_data__util_dot_Shape__pb2._SHAPEPROTO
DESCRIPTOR.message_types_by_name['TypeShapeProto'] = _TYPESHAPEPROTO

TypeShapeProto = _reflection.GeneratedProtocolMessageType('TypeShapeProto', (_message.Message,), dict(
  DESCRIPTOR = _TYPESHAPEPROTO,
  __module__ = 'LAMARCK_ML.data_util.TypeShape_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.TypeShapeProto)
  ))
_sym_db.RegisterMessage(TypeShapeProto)


# @@protoc_insertion_point(module_scope)
