# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/architectures/losses/Loss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/architectures/losses/Loss.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n*LAMARCK_ML/architectures/losses/Loss.proto\x12\nLAMARCK_ML\x1a$LAMARCK_ML/data_util/Attribute.proto\"\x84\x01\n\tLossProto\x12\x10\n\x08\x63ls_name\x18\x01 \x01(\t\x12\x0f\n\x07id_name\x18\x02 \x01(\t\x12*\n\treduction\x18\x05 \x01(\x0e\x32\x17.LAMARCK_ML.ReduceProto\x12(\n\x04\x61ttr\x18\n \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProto*^\n\x0bReduceProto\x12\x08\n\x04MEAN\x10\x00\x12\x0b\n\x07MINIMUM\x10\x01\x12\x0b\n\x07MAXIMUM\x10\x02\x12\x07\n\x03SUM\x10\x03\x12\x0b\n\x07PRODUCT\x10\x04\x12\x0c\n\x08VARIANCE\x10\x05\x12\x07\n\x03STD\x10\x06\x62\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REDUCEPROTO = _descriptor.EnumDescriptor(
  name='ReduceProto',
  full_name='LAMARCK_ML.ReduceProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MEAN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINIMUM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXIMUM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VARIANCE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STD', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=231,
  serialized_end=325,
)
_sym_db.RegisterEnumDescriptor(_REDUCEPROTO)

ReduceProto = enum_type_wrapper.EnumTypeWrapper(_REDUCEPROTO)
MEAN = 0
MINIMUM = 1
MAXIMUM = 2
SUM = 3
PRODUCT = 4
VARIANCE = 5
STD = 6



_LOSSPROTO = _descriptor.Descriptor(
  name='LossProto',
  full_name='LAMARCK_ML.LossProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='LAMARCK_ML.LossProto.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.LossProto.id_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reduction', full_name='LAMARCK_ML.LossProto.reduction', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.LossProto.attr', index=3,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=229,
)

_LOSSPROTO.fields_by_name['reduction'].enum_type = _REDUCEPROTO
_LOSSPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
DESCRIPTOR.message_types_by_name['LossProto'] = _LOSSPROTO
DESCRIPTOR.enum_types_by_name['ReduceProto'] = _REDUCEPROTO

LossProto = _reflection.GeneratedProtocolMessageType('LossProto', (_message.Message,), dict(
  DESCRIPTOR = _LOSSPROTO,
  __module__ = 'LAMARCK_ML.architectures.losses.Loss_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.LossProto)
  ))
_sym_db.RegisterMessage(LossProto)


# @@protoc_insertion_point(module_scope)
