# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/architectures/functions/Function.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.architectures.variables import Variable_pb2 as LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2
from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2
from LAMARCK_ML.architectures import IOMapping_pb2 as LAMARCK__ML_dot_architectures_dot_IOMapping__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/architectures/functions/Function.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n1LAMARCK_ML/architectures/functions/Function.proto\x12\nLAMARCK_ML\x1a\x31LAMARCK_ML/architectures/variables/Variable.proto\x1a$LAMARCK_ML/data_util/Attribute.proto\x1a(LAMARCK_ML/architectures/IOMapping.proto\"\xbf\x01\n\rFunctionProto\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x0f\n\x07id_name\x18\x02 \x01(\t\x12\x31\n\rinput_mapping\x18\x05 \x03(\x0b\x32\x1a.LAMARCK_ML.IOMappingProto\x12(\n\x04\x61ttr\x18\x08 \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProto\x12,\n\tvariables\x18\n \x03(\x0b\x32\x19.LAMARCK_ML.VariableProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2.DESCRIPTOR,LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_IOMapping__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FUNCTIONPROTO = _descriptor.Descriptor(
  name='FunctionProto',
  full_name='LAMARCK_ML.FunctionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_name', full_name='LAMARCK_ML.FunctionProto.class_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.FunctionProto.id_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_mapping', full_name='LAMARCK_ML.FunctionProto.input_mapping', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.FunctionProto.attr', index=3,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variables', full_name='LAMARCK_ML.FunctionProto.variables', index=4,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=388,
)

_FUNCTIONPROTO.fields_by_name['input_mapping'].message_type = LAMARCK__ML_dot_architectures_dot_IOMapping__pb2._IOMAPPINGPROTO
_FUNCTIONPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
_FUNCTIONPROTO.fields_by_name['variables'].message_type = LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2._VARIABLEPROTO
DESCRIPTOR.message_types_by_name['FunctionProto'] = _FUNCTIONPROTO

FunctionProto = _reflection.GeneratedProtocolMessageType('FunctionProto', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTIONPROTO,
  __module__ = 'LAMARCK_ML.architectures.functions.Function_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.FunctionProto)
  ))
_sym_db.RegisterMessage(FunctionProto)


# @@protoc_insertion_point(module_scope)
