# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/architectures/IOMapping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/architectures/IOMapping.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n(LAMARCK_ML/architectures/IOMapping.proto\x12\nLAMARCK_ML\"I\n\x0eIOMappingProto\x12\x10\n\x08in_label\x18\x01 \x01(\t\x12\x11\n\tout_label\x18\x02 \x01(\t\x12\x12\n\ndf_id_name\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IOMAPPINGPROTO = _descriptor.Descriptor(
  name='IOMappingProto',
  full_name='LAMARCK_ML.IOMappingProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_label', full_name='LAMARCK_ML.IOMappingProto.in_label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_label', full_name='LAMARCK_ML.IOMappingProto.out_label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='df_id_name', full_name='LAMARCK_ML.IOMappingProto.df_id_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['IOMappingProto'] = _IOMAPPINGPROTO

IOMappingProto = _reflection.GeneratedProtocolMessageType('IOMappingProto', (_message.Message,), dict(
  DESCRIPTOR = _IOMAPPINGPROTO,
  __module__ = 'LAMARCK_ML.architectures.IOMapping_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.IOMappingProto)
  ))
_sym_db.RegisterMessage(IOMappingProto)


# @@protoc_insertion_point(module_scope)
