# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/architectures/NeuralNetwork.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2
from LAMARCK_ML.architectures.functions import Function_pb2 as LAMARCK__ML_dot_architectures_dot_functions_dot_Function__pb2
from LAMARCK_ML.architectures import IOMapping_pb2 as LAMARCK__ML_dot_architectures_dot_IOMapping__pb2
from LAMARCK_ML.architectures.variables import Variable_pb2 as LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/architectures/NeuralNetwork.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n,LAMARCK_ML/architectures/NeuralNetwork.proto\x12\nLAMARCK_ML\x1a$LAMARCK_ML/data_util/Attribute.proto\x1a\x31LAMARCK_ML/architectures/functions/Function.proto\x1a(LAMARCK_ML/architectures/IOMapping.proto\x1a\x31LAMARCK_ML/architectures/variables/Variable.proto\"\xde\x02\n\x12NeuralNetworkProto\x12\x0f\n\x07id_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66unction_cls\x18\x03 \x03(\t\x12\x34\n\x0boutput_ntss\x18\x04 \x01(\x0b\x32\x1f.LAMARCK_ML.AttributeProto.Dict\x12\x31\n\rinput_mapping\x18\x05 \x03(\x0b\x32\x1a.LAMARCK_ML.IOMappingProto\x12\x32\n\x0eoutput_mapping\x18\x06 \x03(\x0b\x32\x1a.LAMARCK_ML.IOMappingProto\x12,\n\tfunctions\x18\n \x03(\x0b\x32\x19.LAMARCK_ML.FunctionProto\x12,\n\tvariables\x18\x0b \x03(\x0b\x32\x19.LAMARCK_ML.VariableProto\x12(\n\x04\x61ttr\x18\x0f \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_functions_dot_Function__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_IOMapping__pb2.DESCRIPTOR,LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NEURALNETWORKPROTO = _descriptor.Descriptor(
  name='NeuralNetworkProto',
  full_name='LAMARCK_ML.NeuralNetworkProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.NeuralNetworkProto.id_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function_cls', full_name='LAMARCK_ML.NeuralNetworkProto.function_cls', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_ntss', full_name='LAMARCK_ML.NeuralNetworkProto.output_ntss', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_mapping', full_name='LAMARCK_ML.NeuralNetworkProto.input_mapping', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_mapping', full_name='LAMARCK_ML.NeuralNetworkProto.output_mapping', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='functions', full_name='LAMARCK_ML.NeuralNetworkProto.functions', index=5,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variables', full_name='LAMARCK_ML.NeuralNetworkProto.variables', index=6,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.NeuralNetworkProto.attr', index=7,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=593,
)

_NEURALNETWORKPROTO.fields_by_name['output_ntss'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO_DICT
_NEURALNETWORKPROTO.fields_by_name['input_mapping'].message_type = LAMARCK__ML_dot_architectures_dot_IOMapping__pb2._IOMAPPINGPROTO
_NEURALNETWORKPROTO.fields_by_name['output_mapping'].message_type = LAMARCK__ML_dot_architectures_dot_IOMapping__pb2._IOMAPPINGPROTO
_NEURALNETWORKPROTO.fields_by_name['functions'].message_type = LAMARCK__ML_dot_architectures_dot_functions_dot_Function__pb2._FUNCTIONPROTO
_NEURALNETWORKPROTO.fields_by_name['variables'].message_type = LAMARCK__ML_dot_architectures_dot_variables_dot_Variable__pb2._VARIABLEPROTO
_NEURALNETWORKPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
DESCRIPTOR.message_types_by_name['NeuralNetworkProto'] = _NEURALNETWORKPROTO

NeuralNetworkProto = _reflection.GeneratedProtocolMessageType('NeuralNetworkProto', (_message.Message,), dict(
  DESCRIPTOR = _NEURALNETWORKPROTO,
  __module__ = 'LAMARCK_ML.architectures.NeuralNetwork_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.NeuralNetworkProto)
  ))
_sym_db.RegisterMessage(NeuralNetworkProto)


# @@protoc_insertion_point(module_scope)
