# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/individuals/Individual.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/individuals/Individual.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n\'LAMARCK_ML/individuals/Individual.proto\x12\nLAMARCK_ML\x1a$LAMARCK_ML/data_util/Attribute.proto\"\xc7\x01\n\x0fIndividualProto\x12\x10\n\x08\x63ls_name\x18\x01 \x01(\t\x12\x0f\n\x07id_name\x18\x02 \x01(\t\x12\x38\n\x07metrics\x18\x03 \x03(\x0b\x32\'.LAMARCK_ML.IndividualProto.MetricProto\x12(\n\x04\x61ttr\x18\x04 \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProto\x1a-\n\x0bMetricProto\x12\x0f\n\x07id_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INDIVIDUALPROTO_METRICPROTO = _descriptor.Descriptor(
  name='MetricProto',
  full_name='LAMARCK_ML.IndividualProto.MetricProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.IndividualProto.MetricProto.id_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='LAMARCK_ML.IndividualProto.MetricProto.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=293,
)

_INDIVIDUALPROTO = _descriptor.Descriptor(
  name='IndividualProto',
  full_name='LAMARCK_ML.IndividualProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cls_name', full_name='LAMARCK_ML.IndividualProto.cls_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_name', full_name='LAMARCK_ML.IndividualProto.id_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='LAMARCK_ML.IndividualProto.metrics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.IndividualProto.attr', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INDIVIDUALPROTO_METRICPROTO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=293,
)

_INDIVIDUALPROTO_METRICPROTO.containing_type = _INDIVIDUALPROTO
_INDIVIDUALPROTO.fields_by_name['metrics'].message_type = _INDIVIDUALPROTO_METRICPROTO
_INDIVIDUALPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
DESCRIPTOR.message_types_by_name['IndividualProto'] = _INDIVIDUALPROTO

IndividualProto = _reflection.GeneratedProtocolMessageType('IndividualProto', (_message.Message,), dict(

  MetricProto = _reflection.GeneratedProtocolMessageType('MetricProto', (_message.Message,), dict(
    DESCRIPTOR = _INDIVIDUALPROTO_METRICPROTO,
    __module__ = 'LAMARCK_ML.individuals.Individual_pb2'
    # @@protoc_insertion_point(class_scope:LAMARCK_ML.IndividualProto.MetricProto)
    ))
  ,
  DESCRIPTOR = _INDIVIDUALPROTO,
  __module__ = 'LAMARCK_ML.individuals.Individual_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.IndividualProto)
  ))
_sym_db.RegisterMessage(IndividualProto)
_sym_db.RegisterMessage(IndividualProto.MetricProto)


# @@protoc_insertion_point(module_scope)
