# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LAMARCK_ML/utils/CompareClass.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from LAMARCK_ML.data_util import Attribute_pb2 as LAMARCK__ML_dot_data__util_dot_Attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LAMARCK_ML/utils/CompareClass.proto',
  package='LAMARCK_ML',
  syntax='proto3',
  serialized_pb=_b('\n#LAMARCK_ML/utils/CompareClass.proto\x12\nLAMARCK_ML\x1a$LAMARCK_ML/data_util/Attribute.proto\"=\n\x11\x43ompareClassProto\x12(\n\x04\x61ttr\x18\x01 \x03(\x0b\x32\x1a.LAMARCK_ML.AttributeProtob\x06proto3')
  ,
  dependencies=[LAMARCK__ML_dot_data__util_dot_Attribute__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPARECLASSPROTO = _descriptor.Descriptor(
  name='CompareClassProto',
  full_name='LAMARCK_ML.CompareClassProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr', full_name='LAMARCK_ML.CompareClassProto.attr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=150,
)

_COMPARECLASSPROTO.fields_by_name['attr'].message_type = LAMARCK__ML_dot_data__util_dot_Attribute__pb2._ATTRIBUTEPROTO
DESCRIPTOR.message_types_by_name['CompareClassProto'] = _COMPARECLASSPROTO

CompareClassProto = _reflection.GeneratedProtocolMessageType('CompareClassProto', (_message.Message,), dict(
  DESCRIPTOR = _COMPARECLASSPROTO,
  __module__ = 'LAMARCK_ML.utils.CompareClass_pb2'
  # @@protoc_insertion_point(class_scope:LAMARCK_ML.CompareClassProto)
  ))
_sym_db.RegisterMessage(CompareClassProto)


# @@protoc_insertion_point(module_scope)
